# Generated by Django 5.0.1 on 2024-01-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='age',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='author',
            new_name='age',
        ),
    ]
